name: E2E test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
      # build plugin
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
      - run: yarn test:ci

      # run example and test
      - run: yarn install --immutable --immutable-cache
        working-directory: example

      - run: yarn build
        working-directory: example

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: example
        run: |
          pip install -r requirements.txt

      - run: yarn test:e2e:ci
